const plannerList = document.querySelector("#planner-list");
const calendar = document.querySelector("#planner-calendar");
const modal = document.querySelector("#task-modal");
const form = document.querySelector("#task-form");
let courses = [], tasks = [], editing = null, view = "upcoming", calendarDate = new Date();
const qs = new URLSearchParams(location.search);
let shouldAutoOpen = qs.has("new");

function localDay(date) { return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`; }
function dueDate(task) { return new Date(task.dueAt); }
function courseFor(task) { return courses.find(c => c.id === task.courseId) || task; }
function dayDiff(date) { const today = new Date(); today.setHours(0,0,0,0); const day = new Date(date); day.setHours(0,0,0,0); return Math.round((day-today)/86400000); }
function dueLabel(task) { const date=dueDate(task), d=dayDiff(date); const day=d===0?"Today":d===1?"Tomorrow":d<0?`${Math.abs(d)}d overdue`:date.toLocaleDateString(undefined,{month:"short",day:"numeric"}); return `${day} · ${date.toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"})}`; }
function groupLabel(task) { const d=dayDiff(dueDate(task)); if(d<0)return"Overdue"; if(d===0)return"Today"; if(d===1)return"Tomorrow"; if(d<=7)return"This Week"; return"Later"; }

function taskRow(task) {
 const row=document.createElement("article"); const c=courseFor(task); row.className=`planner-task${task.completed?" completed":""}${!task.completed&&dueDate(task)<new Date()?" overdue":""}`;
 row.innerHTML='<input type="checkbox" aria-label="Mark task complete"><span class="task-accent"></span><div class="task-main"><h3></h3><div class="task-meta"><strong class="task-course"></strong><span class="task-type"></span></div></div><div class="task-actions"><span class="task-due"></span><button class="text-button" type="button">Edit</button></div>';
 window.StudySignalCourseColors.applyCourseColor(row,c); row.querySelector("h3").textContent=task.title; row.querySelector(".task-course").textContent=task.courseCode; row.querySelector(".task-type").textContent=task.type; row.querySelector(".task-due").textContent=dueLabel(task);
 const check=row.querySelector("input"); check.checked=task.completed; check.addEventListener("change",async()=>{const before=task.completed;task.completed=check.checked;row.classList.toggle("completed",task.completed);try{const saved=await StudyAI.api.patch(`/api/courses/${task.courseId}/tasks/${task.id}`,{completed:task.completed});Object.assign(task,saved);render();}catch(e){task.completed=before;check.checked=before;row.classList.toggle("completed",before);StudyAI.ui.notify(e.message,{type:"error"});}});
 row.querySelector("button").addEventListener("click",()=>openModal(task.type,task)); return row;
}
function filtered() { const courseId=Number(document.querySelector("#planner-course-filter").value||0), type=document.querySelector("#planner-type-filter").value; return tasks.filter(t=>(!courseId||t.courseId===courseId)&&(!type||t.type===type)); }
function renderGroups() {
 const visible=filtered().filter(t=>view!=="today"||localDay(dueDate(t))===localDay(new Date())); const open=visible.filter(t=>!t.completed), done=visible.filter(t=>t.completed); plannerList.innerHTML="";
 const groups=new Map(); open.forEach(t=>{const label=groupLabel(t);if(!groups.has(label))groups.set(label,[]);groups.get(label).push(t)}); if(done.length)groups.set("Completed",done);
 if(!groups.size){plannerList.innerHTML=`<div class="friendly-empty"><strong>${view==="today"?"Nothing due today":"No upcoming deadlines"}</strong><span>Add an assignment or exam to start planning.</span><button class="text-button" data-empty-add>Add Assignment</button></div>`;plannerList.querySelector("[data-empty-add]").onclick=()=>openModal("assignment");return;}
 for(const [label,items] of groups){const section=document.createElement("section");section.className="planner-group";section.innerHTML='<h2></h2><div class="planner-group-list"></div>';section.querySelector("h2").textContent=label;items.forEach(t=>section.querySelector("div").appendChild(taskRow(t)));plannerList.appendChild(section)}
}
function renderCalendar(){calendar.innerHTML="";const year=calendarDate.getFullYear(),month=calendarDate.getMonth(),first=new Date(year,month,1),start=new Date(year,month,1-first.getDay());const heading=document.createElement("div");heading.className="calendar-heading";heading.innerHTML='<button class="icon-button" aria-label="Previous month">←</button><h2></h2><button class="icon-button" aria-label="Next month">→</button>';heading.querySelector("h2").textContent=first.toLocaleDateString(undefined,{month:"long",year:"numeric"});const buttons=heading.querySelectorAll("button");buttons[0].onclick=()=>{calendarDate=new Date(year,month-1,1);renderCalendar()};buttons[1].onclick=()=>{calendarDate=new Date(year,month+1,1);renderCalendar()};calendar.appendChild(heading);const grid=document.createElement("div");grid.className="calendar-grid";["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].forEach(x=>{const h=document.createElement("strong");h.className="calendar-date";h.textContent=x;grid.appendChild(h)});for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const cell=document.createElement("div");cell.className=`calendar-day${d.getMonth()!==month?" muted":""}`;cell.innerHTML='<span class="calendar-date"></span>';cell.querySelector("span").textContent=d.getDate();filtered().filter(t=>localDay(dueDate(t))===localDay(d)).slice(0,3).forEach(t=>{const dot=document.createElement("span");dot.className="calendar-dot";window.StudySignalCourseColors.applyCourseColor(dot,courseFor(t));dot.textContent=t.title;cell.appendChild(dot)});grid.appendChild(cell)}calendar.appendChild(grid)}
function render(){plannerList.hidden=view==="calendar";calendar.hidden=view!=="calendar";view==="calendar"?renderCalendar():renderGroups();document.querySelectorAll("[data-view]").forEach(b=>b.setAttribute("aria-selected",String(b.dataset.view===view)));}
async function loadLinks(courseId){const [units,materials]=await Promise.all([StudyAI.api.get(`/api/courses/${courseId}/units`),StudyAI.api.get(`/api/courses/${courseId}/materials`)]);const fill=(el,items,label)=>{el.innerHTML=`<option value="">No ${label}</option>`;items.forEach(x=>{const o=document.createElement("option");o.value=x.id;o.textContent=x.name||x.displayName;el.appendChild(o)})};fill(document.querySelector("#task-unit"),units,"unit");fill(document.querySelector("#task-material"),materials,"material");}
async function openModal(type="assignment",task=null){if(!courses.length){StudyAI.ui.notify("Create a course before adding planner items.",{type:"error"});return}editing=task;form.reset();document.querySelector("#task-modal-title").textContent=task?"Edit Planner Item":`Add ${type[0].toUpperCase()+type.slice(1)}`;const courseId=task?.courseId||Number(qs.get("courseId"))||courses[0].id;document.querySelector("#task-course").value=courseId;document.querySelector("#task-type").value=task?.type||type;await loadLinks(courseId);if(task){document.querySelector("#task-title").value=task.title;document.querySelector("#task-description").value=task.description||"";const date=dueDate(task);document.querySelector("#task-date").value=localDay(date);document.querySelector("#task-time").value=`${String(date.getHours()).padStart(2,"0")}:${String(date.getMinutes()).padStart(2,"0")}`;document.querySelector("#task-unit").value=task.unitId||"";document.querySelector("#task-material").value=task.materialId||"";document.querySelector("#task-minutes").value=task.estimatedMinutes||""}document.querySelector("#delete-task").hidden=!task;modal.classList.add("open")}
function closeModal(){modal.classList.remove("open");editing=null;document.querySelector("#task-form-error").textContent=""}
document.querySelectorAll("[data-add-type]").forEach(b=>b.onclick=()=>openModal(b.dataset.addType));document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelectorAll("#planner-course-filter,#planner-type-filter").forEach(e=>e.onchange=render);document.querySelector("#close-task-modal").onclick=closeModal;document.querySelector("#cancel-task").onclick=closeModal;document.querySelector("#task-course").onchange=e=>loadLinks(Number(e.target.value));
form.onsubmit=async e=>{e.preventDefault();const button=document.querySelector("#save-task"),wasEditing=Boolean(editing);button.disabled=true;try{const date=document.querySelector("#task-date").value,time=document.querySelector("#task-time").value||"23:59",payload={title:document.querySelector("#task-title").value,type:document.querySelector("#task-type").value,dueAt:new Date(`${date}T${time}:00`).toISOString(),description:document.querySelector("#task-description").value,unitId:document.querySelector("#task-unit").value||null,materialId:document.querySelector("#task-material").value||null,estimatedMinutes:document.querySelector("#task-minutes").value||null},courseId=Number(document.querySelector("#task-course").value);if(editing&&editing.courseId!==courseId){throw new Error("Move between courses by creating a new planner item.")}if(editing)await StudyAI.api.patch(`/api/courses/${courseId}/tasks/${editing.id}`,payload);else await StudyAI.api.post(`/api/courses/${courseId}/tasks`,payload);closeModal();await initialize();StudyAI.ui.notify(wasEditing?"Planner item updated.":"Planner item added.",{type:"success"})}catch(err){document.querySelector("#task-form-error").textContent=err.message}finally{button.disabled=false}};
document.querySelector("#delete-task").onclick=async()=>{if(!editing)return;const button=document.querySelector("#delete-task");button.disabled=true;try{await StudyAI.api.delete(`/api/courses/${editing.courseId}/tasks/${editing.id}`);closeModal();await initialize();StudyAI.ui.notify("Planner item deleted.",{type:"success"})}catch(e){document.querySelector("#task-form-error").textContent=e.message}finally{button.disabled=false}};
async function initialize(){try{[courses,tasks]=await Promise.all([StudyAI.api.get("/api/courses"),StudyAI.api.get("/api/tasks")]);for(const id of ["task-course","planner-course-filter"]){const select=document.querySelector(`#${id}`),first=select.options[0]?.cloneNode(true);select.innerHTML="";if(first&&id.includes("filter"))select.appendChild(first);courses.forEach(c=>{const o=document.createElement("option");o.value=c.id;o.textContent=`${c.courseCode} — ${c.courseName}`;select.appendChild(o)})}if(qs.get("courseId"))document.querySelector("#planner-course-filter").value=qs.get("courseId");render();if(shouldAutoOpen){shouldAutoOpen=false;openModal(qs.get("type")||"assignment")}}catch(e){plannerList.innerHTML='<div class="friendly-empty error-state"></div>';plannerList.firstChild.textContent=e.message}}
initialize();
