(function(){const courseId=StudyAI.courseContext.getCourseId(),modal=document.querySelector("#schedule-import-modal"),sourceStep=document.querySelector("#schedule-source-step"),reviewStep=document.querySelector("#schedule-review-step"),materialSelect=document.querySelector("#schedule-material"),candidatesBox=document.querySelector("#schedule-candidates"),error=document.querySelector("#schedule-import-error");let preview=null;
function close(){modal.classList.remove("open");error.textContent="";reviewStep.hidden=true;sourceStep.hidden=false;preview=null}
async function open(){modal.classList.add("open");error.textContent="";const materials=await StudyAI.api.get(`/api/courses/${courseId}/materials`);materialSelect.innerHTML="";materials.filter(x=>x.extractionStatus==="extracted").forEach(x=>materialSelect.add(new Option(`${x.displayName}${x.materialRole==="syllabus"?" · Syllabus":""}`,x.id)));if(!materialSelect.options.length){materialSelect.add(new Option("No extracted materials available",""));$("#preview-schedule").disabled=true}}
const $=s=>document.querySelector(s);
function row(candidate){const item=document.createElement("article");item.className=`schedule-candidate ${candidate.status} ${candidate.importState}`;item.dataset.key=candidate.key;item.innerHTML='<label class="candidate-check"><input type="checkbox"><span></span></label><div class="candidate-fields"><input class="candidate-title" maxlength="200"><select class="candidate-type"><option value="assignment">Assignment</option><option value="exam">Exam</option><option value="quiz">Quiz</option><option value="reading">Reading</option><option value="project">Project</option><option value="paper">Paper</option><option value="other">Other</option></select><div><input class="candidate-date" type="date"><input class="candidate-time" type="time"></div><small class="candidate-state"></small><blockquote></blockquote></div>';const check=item.querySelector("input[type=checkbox]");check.checked=candidate.selected;check.disabled=candidate.importState==="already_imported";item.querySelector(".candidate-title").value=candidate.title;item.querySelector(".candidate-type").value=candidate.type;item.querySelector(".candidate-date").value=candidate.dueDate||"";item.querySelector(".candidate-time").value=candidate.dueTime||"";item.querySelector(".candidate-state").textContent=candidate.importState==="already_imported"?"Already imported":candidate.status==="ambiguous"?"⚠ Date needs review":"New · explicit date";item.querySelector("blockquote").textContent=`Source: “${candidate.sourceText}”`;return item}
async function find(){error.textContent="";try{preview=await StudyAI.api.post(`/api/courses/${courseId}/schedule-import/preview`,{materialId:Number(materialSelect.value)});sourceStep.hidden=true;reviewStep.hidden=false;candidatesBox.innerHTML="";preview.candidates.forEach(x=>candidatesBox.appendChild(row(x)));$("#schedule-summary").textContent=`Found ${preview.candidates.length} possible deadlines · ${preview.summary.confirmed} clear · ${preview.summary.ambiguous} need review`;$("#schedule-confirm-copy").hidden=true;$("#import-schedule-events").dataset.confirmed="false"}catch(e){error.textContent=e.message}}
function selected(){return[...candidatesBox.querySelectorAll(".schedule-candidate")].filter(x=>x.querySelector("input[type=checkbox]").checked).map(x=>{const date=x.querySelector(".candidate-date").value,time=x.querySelector(".candidate-time").value||"23:59";return{key:x.dataset.key,title:x.querySelector(".candidate-title").value,type:x.querySelector(".candidate-type").value,dueAt:date?new Date(`${date}T${time}:00`).toISOString():null}})}
async function submit(){const button=$("#import-schedule-events"),items=selected();error.textContent="";if(!items.length)return error.textContent="Select at least one resolved deadline.";if(items.some(x=>!x.dueAt))return error.textContent="Every selected event needs a valid date.";if(button.dataset.confirmed!=="true"){$("#schedule-confirm-copy").textContent=`Create ${items.length} Planner event${items.length===1?"":"s"}? Review the dates above, then confirm.`;$("#schedule-confirm-copy").hidden=false;button.dataset.confirmed="true";button.textContent="Confirm Import";return}try{const result=await StudyAI.api.post(`/api/courses/${courseId}/schedule-import/confirm`,{materialId:preview.material.id,candidates:items});StudyAI.ui.notify(`${result.created} events created · ${result.skipped} skipped`,{type:"success"});close();await window.location.reload()}catch(e){error.textContent=e.message}}
$("#import-course-schedule").onclick=open;$("#close-schedule-import").onclick=close;$("#preview-schedule").onclick=find;$("#back-schedule-import").onclick=()=>{reviewStep.hidden=true;sourceStep.hidden=false};$("#import-schedule-events").onclick=submit;$("#upload-schedule-material").href=`materials.html?courseId=${courseId}&upload=1`;})();
