const crypto = require("crypto");
const MONTHS = { jan:1,january:1,feb:2,february:2,mar:3,march:3,apr:4,april:4,may:5,jun:6,june:6,jul:7,july:7,aug:8,august:8,sep:9,sept:9,september:9,oct:10,october:10,nov:11,november:11,dec:12,december:12 };
const ACADEMIC_EVENT = /\b(assignment|homework|problem set|quiz|exam|midterm|final(?: exam)?|project|paper|presentation|reading|lab|discussion)\b/i;
const SCHEDULE_HEADING = /^(?:(?:course\s+)?(?:schedule|calendar)|(?:weekly|important dates?|assignment|exam|tentative)\s+(?:schedule|calendar|dates?))$/i;
const GENERIC_HEADING = /^[A-Z][A-Za-z &/()-]{2,50}:?$/;
const SUPPRESSED_CONTEXT = /\b(office hours?|instructor|teaching assistant|\bta\b|contact|phone|telephone|email|accommodations?|accessibility|disability|policy|policies|copyright|published|publication|textbook|isbn)\b/i;
const RELATIVE_DATE = /\b(following|next)\s+(mon|tues|wednes|thurs|fri|satur|sun)day\b|\bduring finals week\b|\bbefore class\b|\blast day of class\b/i;
function semesterYear(value) { const match=String(value||"").match(/\b(20\d{2})\b/); return match?Number(match[1]):null; }
function validDate(year,month,day) { const date=new Date(year,month-1,day); return date.getFullYear()===year&&date.getMonth()===month-1&&date.getDate()===day; }
function isReview(text) { return /\b(?:exam|midterm|final)\s*\d*\s+review\b|\breview\s+(?:for\s+)?(?:exam|midterm|final)\b/i.test(text); }
function typeFor(text) { if(isReview(text))return"other";if(/\b(midterm|final exam|exam)\b/i.test(text))return"exam";if(/\bquiz\b/i.test(text))return"quiz";if(/\b(project|presentation)\b/i.test(text))return"project";if(/\bpaper\b/i.test(text))return"paper";if(/\breading\b/i.test(text))return"reading";return/\b(assignment|homework|problem set)\b/i.test(text)?"assignment":"other"; }
function parseDate(line,contextYear) {
 let match=line.match(/\b(January|February|March|April|May|June|July|August|September|Sept\.?|Sep\.?|October|November|December|Jan\.?|Feb\.?|Mar\.?|Apr\.?|Jun\.?|Jul\.?|Aug\.?|Oct\.?|Nov\.?|Dec\.?)\s+(\d{1,2})(?:,?\s+(20\d{2}))?/i);
 if(match){const month=MONTHS[match[1].toLowerCase().replace(".","")],year=Number(match[3]||contextYear);return year&&validDate(year,month,Number(match[2]))?{date:`${year}-${String(month).padStart(2,"0")}-${String(Number(match[2])).padStart(2,"0")}`,text:match[0],inferred:!match[3]}:null;}
 match=line.match(/\b(\d{1,2})\/(\d{1,2})(?:\/(20\d{2}|\d{2}))?\b/);
 if(match){let year=match[3]?Number(match[3]):contextYear;if(year&&year<100)year+=2000;return year&&validDate(year,Number(match[1]),Number(match[2]))?{date:`${year}-${match[1].padStart(2,"0")}-${match[2].padStart(2,"0")}`,text:match[0],inferred:!match[3]}:null;}
 return null;
}
function parseTime(line) { const range=line.match(/\b(\d{1,2})(?::(\d{2}))?\s*(?:AM|PM)?\s*[-–—]\s*\d{1,2}(?::\d{2})?\s*(AM|PM)\b/i),match=range||line.match(/\b(\d{1,2})(?::(\d{2}))?\s*(AM|PM)\b/i);if(!match)return null;let hour=Number(match[1])%12;if(match[3].toUpperCase()==="PM")hour+=12;return`${String(hour).padStart(2,"0")}:${match[2]||"00"}`; }
function scheduleLines(text) { const lines=String(text||"").split(/\r?\n/).map((raw,index)=>({raw:raw.trim(),line:raw.replace(/\s+/g," ").trim(),index}));let inSchedule=false,foundSchedule=false;return lines.map(entry=>{if(SCHEDULE_HEADING.test(entry.line.replace(/:$/,"").trim())){inSchedule=true;foundSchedule=true;return{...entry,isHeading:true,inSchedule:false}}if(inSchedule&&GENERIC_HEADING.test(entry.line)&&!parseDate(entry.line,null)&&!ACADEMIC_EVENT.test(entry.line))inSchedule=false;return{...entry,inSchedule}}).map(entry=>({...entry,hasSchedule:foundSchedule})); }
function cleanScheduleTitle(line,dateText) { let title=line.replace(dateText||"","").trim();title=title.replace(/^(?:\||[-–—]\s*)?(?:M|T|W|Th|F|Sa|Su|Mon|Tue|Tues|Wed|Thu|Thur|Fri|Sat|Sun)\b\.?\s*/i,"");title=title.replace(/^\s*(?:\||[-–—])+\s*/,"").replace(/\s*(?:\||[-–—])+\s*(?:\d+\s*)?(?:\||[-–—\s])*$/g,"");title=title.replace(/\s*\([^)]*(?:\d{1,2}\s*[-–—]\s*\d{1,2}\s*(?:am|pm)|\d{3,5}\s+[A-Z]{2,})[^)]*\)\s*/ig," ");const event=title.match(/\b(?:Exam\s*\d+\s+Review|Midterm\s*\d*\s+Review|Final(?: Exam)?\s+Review|Exam\s*\d+|Midterm\s*\d*|Final Exam|Final|(?:Homework|HW|Assignment|Problem Set|Quiz|Project|Paper|Presentation)\s*[A-Za-z0-9.-]*)\b/i);return(event?.[0]||title).replace(/\s+/g," ").trim().slice(0,200)||"Scheduled coursework"; }
function proseTitle(line,dateText) { return line.replace(/^\s*(?:week\s*\d+\s*[-–—|:]\s*)?/i,"").replace(dateText||"","").replace(/\b(?:due|held|on|at)\b\s*[:–—-]?\s*$/i,"").replace(/[|–—-]+\s*$/g,"").trim().slice(0,200)||"Scheduled coursework"; }
function parseSchedule(text,{semester="",materialId,maxCandidates=100}={}) { const year=semesterYear(semester),candidates=[],seen=new Set(),entries=scheduleLines(text),hasSchedule=entries.some(x=>x.hasSchedule);for(const entry of entries){const{line,raw,inSchedule,isHeading}=entry;if(!line||isHeading||SUPPRESSED_CONTEXT.test(line)||/%/.test(line)||(!hasSchedule&&!inSchedule&&line.includes("|")&&!/\b(due|deadline|held)\b/i.test(line)))continue;const parsed=parseDate(line,year),relative=RELATIVE_DATE.test(line),academic=ACADEMIC_EVENT.test(line),review=isReview(line),explicitDue=/\b(due|deadline|held)\b/i.test(line);if(!academic)continue;if(hasSchedule&&!inSchedule&&!explicitDue)continue;if(!inSchedule&&!parsed&&!relative)continue;if(inSchedule&&!parsed&&!relative)continue;const title=inSchedule?cleanScheduleTitle(line,parsed?.text):proseTitle(line,parsed?.text);if(!ACADEMIC_EVENT.test(title))continue;let confidence=inSchedule&&parsed&&!review?"high":parsed?"moderate":"low";if(explicitDue&&parsed&&inSchedule)confidence="high";const ambiguous=!parsed||relative&&!parsed,selected=!ambiguous&&confidence!=="low"&&!review,key=crypto.createHash("sha256").update(`${materialId}|${line.toLowerCase()}`).digest("hex");if(seen.has(key))continue;seen.add(key);const type=typeFor(title);candidates.push({key,title,type,eventKind:review?"exam_review":type,dateText:parsed?.text||null,dueDate:parsed?.date||null,dueTime:parseTime(line),sourceText:(raw||line).slice(0,500),confidence,status:ambiguous?"ambiguous":"confirmed",selected,yearInferred:Boolean(parsed?.inferred)});if(candidates.length>=maxCandidates)break}return{parserMode:"deterministic",candidates,summary:{confirmed:candidates.filter(x=>x.status==="confirmed").length,ambiguous:candidates.filter(x=>x.status==="ambiguous").length,highConfidence:candidates.filter(x=>x.confidence==="high").length,other:candidates.filter(x=>x.confidence!=="high").length}}; }
module.exports={parseSchedule,parseDate,parseTime,semesterYear,typeFor,isReview,scheduleLines};
